FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy the code
COPY . .

# Build
RUN go build -o clients-api main.go

# Expose api port
EXPOSE 8080

CMD [ "./clients-api" ]
